version: '3'

services:
  frontend:
    image: lightxlamp/udemy-time-app-frontend-dev
    restart: always
    ports:
      - '3333:3333'
  api:
    image: lightxlamp/udemy-time-app-api-dev
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql  
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_data_pub: